// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8WYACRqoZK6eY0pbgj4XBMpi7kAiVrbY',
    appId: '1:1085719067312:web:ab5310d46d1a4523f45975',
    messagingSenderId: '1085719067312',
    projectId: 'jbushapogu-cmsc5303-flutter',
    authDomain: 'jbushapogu-cmsc5303-flutter.firebaseapp.com',
    storageBucket: 'jbushapogu-cmsc5303-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiVil36FnbfkKDwv0cuVpWnB-u611kdjg',
    appId: '1:1085719067312:android:991ddcdab194df91f45975',
    messagingSenderId: '1085719067312',
    projectId: 'jbushapogu-cmsc5303-flutter',
    storageBucket: 'jbushapogu-cmsc5303-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpTIGoO2aR4sDuJcP-5MmiBg7ONjy8zOQ',
    appId: '1:1085719067312:ios:eedf29a05658d5c8f45975',
    messagingSenderId: '1085719067312',
    projectId: 'jbushapogu-cmsc5303-flutter',
    storageBucket: 'jbushapogu-cmsc5303-flutter.appspot.com',
    iosBundleId: 'edu.uco.jbushapogu.cmsc5303.lesson6',
  );

}